import { useEffect, useMemo, useState } from 'react'
import { ExternalLink, FileDiff, KeyRound, Plus, Save, Search, ShieldCheck, Trash2 } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Button } from '../../components/ui/button'
import { AppDialog } from '../../components/ui/dialog'
import { useUnsavedChangesGuard } from '../../hooks/use-unsaved-changes-guard'
import { EntityNotFound, FieldRow, MockBoundaryNote, MonoPath, PageHeader, PathActions, StatusBadge, toneForStatus } from '../../components/app/page'
import { useApp } from '../../state'
import { getEligibleMemorySpaces, resolveMemoryGovernance } from '../../memory-policy'
import type { FullAgent } from '../../domain'
import { getFilesForAgentSection, getPrimarySectionForAgentFile, resolveAgentConfigRoute, type AgentConfigSection, type AgentFileView } from '../../agent-config-projection'
import { AgentPackageTree } from './agent-package-files'
import { AgentConfigFilesNav, AgentConfigNavigation } from './agent-config-navigation'
import { AgentConfigFileViewer } from './agent-config-file-viewer'

export function AgentDetailPage() {
  const { id } = useParams()
  const { state, dispatch } = useApp()
  const [params, setParams] = useSearchParams()
  const agent = state.agents.find((item) => item.id === id)
  const [dirty, setDirty] = useState(false)
  const [allFiles, setAllFiles] = useState(false)
  const [routeNotice, setRouteNotice] = useState<string>()
  const unsavedDialog = useUnsavedChangesGuard({ dirty, resetDraft: () => setDirty(false) })
  const route = useMemo(() => agent ? resolveAgentConfigRoute(agent, params) : undefined, [agent, params])
  const projectionContext = useMemo(() => ({ assets: state.assets, workspaces: state.workspaces, memorySpaces: state.memorySpaces }), [state.assets, state.memorySpaces, state.workspaces])

  useEffect(() => {
    if (!route?.needsReplace) return
    setRouteNotice(route.notice)
    setParams(route.canonicalParams, { replace: true })
  }, [route, setParams])

  if (!agent || !route) return <EntityNotFound entity="Agent" backTo="/agents" />
  const relatedFiles = getFilesForAgentSection(agent, route.section)
  const updateParams = (update: (next: URLSearchParams) => void) => { const next = new URLSearchParams(params); update(next); setParams(next) }
  const changeSection = (section: AgentConfigSection) => { setAllFiles(false); updateParams((next) => { if (section === 'overview') next.delete('tab'); else next.set('tab', section); next.delete('path'); next.delete('view') }) }
  const showStructured = () => { setAllFiles(false); updateParams((next) => { next.delete('path'); next.delete('view') }) }
  const showFile = (path: string) => { setAllFiles(false); updateParams((next) => { next.set('tab', getPrimarySectionForAgentFile(agent, path) ?? route.section); next.set('path', path); next.set('view', 'preview') }) }
  const changeView = (view: AgentFileView) => updateParams((next) => next.set('view', view))

  return <>
    <PageHeader backTo="/agents" backLabel="返回 Agents" title={agent.name} description={`${agent.role} · ${agent.department}`} action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'source', agentId: agent.id, section: route.section } })}><Search size={16} aria-hidden="true" />诊断来源</Button><Button onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'client-guide', workspaceId: state.currentWorkspaceId ?? undefined } })}><ExternalLink size={16} aria-hidden="true" />客户端使用指引</Button></div>} />
    <div className="mb-4 flex flex-wrap items-center gap-3"><StatusBadge tone={toneForStatus(agent.status)}>{agent.status}</StatusBadge><StatusBadge tone={toneForStatus(agent.config)}>{agent.config}</StatusBadge><MonoPath>{agent.packagePath}</MonoPath></div>
    {routeNotice && <div role="status" className="mb-4 flex items-center justify-between gap-3 rounded-lg border border-warning/30 bg-warning/8 p-3 text-sm"><span>{routeNotice}</span><button type="button" className="rounded px-2 py-1 text-xs font-medium hover:bg-warning/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" onClick={() => setRouteNotice(undefined)}>知道了</button></div>}
    <div className="grid min-w-0 gap-5 xl:grid-cols-[280px_minmax(0,1fr)]">
      <aside className="panel h-fit p-3"><AgentConfigNavigation active={route.section} onSelect={changeSection} /><AgentConfigFilesNav files={relatedFiles} selectedPath={route.path} allFiles={allFiles} onStructured={showStructured} onSelect={showFile} onAllFiles={() => setAllFiles(true)} />{allFiles && <div className="mt-4 border-t border-border pt-3 xl:hidden"><AgentPackageTree files={agent.files} selectedPath={route.path} onSelect={showFile} ariaLabel={`${agent.name} AgentPackage 目录`} /></div>}{allFiles && <div className="hidden border-t border-border xl:mt-4 xl:block"><div className="label px-3 pt-4">全部文件</div><AgentPackageTree files={agent.files} selectedPath={route.path} onSelect={showFile} ariaLabel={`${agent.name} AgentPackage 目录`} /></div>}</aside>
      <main className="min-w-0">{route.path ? <AgentConfigFileViewer agent={agent} context={projectionContext} path={route.path} view={route.view} onView={changeView} onBack={showStructured} /> : <AgentConfigContent section={route.section} agent={agent} onDirty={setDirty} />}</main>
    </div>
    {unsavedDialog}
  </>
}

function AgentConfigContent({ section, agent, onDirty }: { section: AgentConfigSection; agent: FullAgent; onDirty: (value: boolean) => void }) {
  if (section === 'overview') return <Overview agent={agent} />
  if (section === 'identity') return <IdentityTab agent={agent} onDirty={onDirty} />
  if (section === 'instructions') return <InstructionsTab agent={agent} onDirty={onDirty} />
  if (section === 'skills') return <ReferenceTab agent={agent} kind="Skills" field="skillRefs" onDirty={onDirty} />
  if (section === 'memory') return <MemoryTab agent={agent} />
  if (section === 'rules') return <ReferenceTab agent={agent} kind="Rules" field="ruleRefs" onDirty={onDirty} />
  if (section === 'mcp') return <ReferenceTab agent={agent} kind="MCP" field="mcpRefs" onDirty={onDirty} />
  if (section === 'permissions') return <PermissionsTab agent={agent} onDirty={onDirty} />
  if (section === 'workspaces') return <WorkspacesTab agent={agent} />
  return <SopTab agent={agent} />
}

function Overview({ agent }: { agent: FullAgent }) {
  const { state, dispatch } = useApp()
  return <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><section className="panel p-5"><div className="label">岗位使命</div><p className="mt-3 max-w-3xl leading-7">{agent.mission}</p><div className="mt-7 label">配置完整度</div><div className="mt-3 flex flex-wrap gap-2">{[['身份', true], ['Instructions', Boolean(agent.instructions)], ['Skills', agent.skillRefs.length], ['Memory', state.memorySpaces.filter((item) => item.owner.includes(agent.name)).length], ['Rules', agent.ruleRefs.length], ['MCP', agent.mcpRefs.length], ['Workspaces', agent.workspaceBindings.length], ['SOP', agent.sopRefs.length]].map(([label, count]) => <span key={String(label)} className="rounded-md border border-border bg-muted/30 px-2.5 py-1.5 text-xs">{String(label)} {count === true ? '✓' : String(count)}</span>)}</div><div className="mt-7"><PathActions path={agent.packagePath} /></div></section><aside className="space-y-4"><div className="panel border-l-[3px] border-l-warning p-4"><div className="label">需要处理</div><p className="mt-3 text-sm">{agent.config === '外部变化' ? 'instructions.md 在外部被修改' : agent.config}</p>{agent.config === '外部变化' && <Button className="mt-4" variant="outline" size="sm" onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'diff', agentId: agent.id, path: `${agent.packagePath}instructions.md` } })}><FileDiff size={14} />查看 Diff</Button>}</div><div className="panel p-4"><div className="label">最近保存</div><p className="mt-3 text-sm text-success">演示记录：{agent.updated}</p><p className="mt-2"><MonoPath>{agent.packagePath}</MonoPath></p></div></aside></div>
}

function IdentityTab({ agent, onDirty }: { agent: FullAgent; onDirty: (value: boolean) => void }) {
  const { state, dispatch } = useApp()
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState(agent)
  useEffect(() => { setDraft(agent) }, [agent])
  const update = <K extends keyof FullAgent>(key: K, value: FullAgent[K]) => { setDraft((item) => ({ ...item, [key]: value })); onDirty(true) }
  const cancel = () => { setDraft(agent); setEditing(false); onDirty(false) }
  const save = () => { dispatch({ type: 'UPDATE_AGENT', agentId: agent.id, changes: draft, message: `已更新 ${agent.name} 身份与职责 · 目标：${agent.packagePath}agent.yaml · 仅内存 · 未写盘` }); setEditing(false); onDirty(false) }
  return <section className="panel overflow-hidden"><TabHeader title="身份与职责" description="组织身份、职责和服务授权不形成隐式权限。" editing={editing} onEdit={() => setEditing(true)} onCancel={cancel} onSave={save} />
    <div className="p-5">{editing ? <div className="grid gap-5 sm:grid-cols-2"><Labeled label="名称"><input value={draft.name} onChange={(e) => update('name', e.target.value)} className="h-10 w-full px-3" /></Labeled><Labeled label="岗位"><input value={draft.role} onChange={(e) => update('role', e.target.value)} className="h-10 w-full px-3" /></Labeled><Labeled label="主属部门"><select value={draft.primaryDepartmentId} onChange={(e) => { const dep = state.departments.find((item) => item.id === e.target.value); setDraft((item) => ({ ...item, primaryDepartmentId: e.target.value, department: dep?.name ?? item.department })); onDirty(true) }} className="h-10 w-full px-3">{state.departments.filter((item) => item.companyId === draft.companyId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Labeled><Labeled label="使命"><textarea value={draft.mission} onChange={(e) => update('mission', e.target.value)} className="min-h-28 w-full p-3" /></Labeled><ListEditor label="主要职责" values={draft.responsibilities} onChange={(value) => update('responsibilities', value)} /><ListEditor label="交付物" values={draft.deliverables} onChange={(value) => update('deliverables', value)} /><ListEditor label="决策边界" values={draft.decisionBoundaries} onChange={(value) => update('decisionBoundaries', value)} /><ListEditor label="升级条件" values={draft.escalationConditions} onChange={(value) => update('escalationConditions', value)} /><ListEditor label="禁止事项" values={draft.prohibitions} onChange={(value) => update('prohibitions', value)} /><ListEditor label="完成定义" values={draft.completionDefinition} onChange={(value) => update('completionDefinition', value)} /></div> : <div><FieldRow label="主属部门">{agent.department}（唯一）</FieldRow><FieldRow label="直属主管">{state.agents.find((item) => item.id === agent.managerAgentId)?.name ?? '未设置'}</FieldRow><FieldRow label="使命">{agent.mission}</FieldRow><FieldRow label="主要职责">{agent.responsibilities.join('；')}</FieldRow><FieldRow label="交付物">{agent.deliverables.join('；')}</FieldRow><FieldRow label="决策边界">{agent.decisionBoundaries.join('；')}</FieldRow><FieldRow label="升级条件">{agent.escalationConditions.join('；')}</FieldRow><FieldRow label="禁止事项">{agent.prohibitions.join('；')}</FieldRow><FieldRow label="完成定义">{agent.completionDefinition.join('；')}</FieldRow><FieldRow label="服务授权">{agent.serviceGrants.length ? agent.serviceGrants.map((grant) => `${state.departments.find((item) => item.id === grant.departmentId)?.name}：${grant.capabilities.join('、')}（${grant.status}）`).join('；') : '无跨部门服务授权'}</FieldRow></div>}
      {!editing && <div className="mt-6 flex flex-wrap gap-2"><Button variant="outline" onClick={() => dispatch({ type: 'SET_AGENT_LIFECYCLE', agentId: agent.id, status: agent.status === '停用' ? '启用' : '停用' })}>{agent.status === '停用' ? '重新启用' : '停用 Agent'}</Button><Button variant="outline" onClick={() => dispatch({ type: 'SET_AGENT_LIFECYCLE', agentId: agent.id, status: '归档' })}>归档</Button><Button variant="danger" onClick={() => dispatch({ type: 'TOAST', text: `永久删除仅展示影响：${agent.workspaceBindings.length} WorkspaceBinding、${agent.sopRefs.length} SOP 引用和正式记忆将保留；演示未删除对象` })}><Trash2 size={15} />预览永久删除影响</Button></div>}
    </div></section>
}

function InstructionsTab({ agent, onDirty }: { agent: FullAgent; onDirty: (value: boolean) => void }) {
  const { dispatch } = useApp(); const [editing, setEditing] = useState(false); const [text, setText] = useState(agent.instructions)
  useEffect(() => setText(agent.instructions), [agent.instructions])
  const cancel = () => { setText(agent.instructions); setEditing(false); onDirty(false) }
  const save = () => { dispatch({ type: 'SAVE_INSTRUCTIONS', agentId: agent.id, text }); setEditing(false); onDirty(false) }
  return <section className="panel overflow-hidden"><TabHeader title="Instructions" description={`保存目标：${agent.packagePath}instructions.md`} editing={editing} onEdit={() => setEditing(true)} onCancel={cancel} onSave={save} /><div className="p-5">{editing ? <textarea value={text} onChange={(event) => { setText(event.target.value); onDirty(true) }} className="min-h-72 w-full resize-y p-4 text-sm leading-7" aria-label="Instructions 正文" /> : <div className="whitespace-pre-wrap rounded-lg bg-muted/40 p-5 text-sm leading-7">{agent.instructions}</div>}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground"><span>Agent 自有正文 · 显式引用 {agent.ruleRefs.length} 条 Rule</span><Button variant="ghost" size="sm" onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'diff', agentId: agent.id, path: `${agent.packagePath}instructions.md` } })}><FileDiff size={14} />查看 Diff</Button></div></div></section>
}

function ReferenceTab({ agent, kind, field, onDirty }: { agent: FullAgent; kind: 'Skills' | 'Rules' | 'MCP'; field: 'skillRefs' | 'ruleRefs' | 'mcpRefs'; onDirty: (value: boolean) => void }) {
  const { state, dispatch } = useApp(); const [editing, setEditing] = useState(false); const [refs, setRefs] = useState<string[]>(agent[field]); const candidates = state.assets.filter((item) => item.kind === kind.slice(0, -1) || (kind === 'Rules' && item.kind === 'Rules') || (kind === 'MCP' && item.kind === 'MCP')).filter((item) => kind !== 'Skills' || item.skill?.installation.status !== 'available' || refs.includes(item.id))
  useEffect(() => setRefs(agent[field]), [agent, field])
  const toggle = (id: string) => { setRefs((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); onDirty(true) }
  const save = () => { dispatch({ type: 'UPDATE_AGENT', agentId: agent.id, changes: { [field]: refs }, message: `${kind} 引用已更新 · 目标：${agent.packagePath}config/ · 仅内存 · 未写盘` }); setEditing(false); onDirty(false) }
  return <section className="panel overflow-hidden"><TabHeader title={kind} description="自有配置与显式共享引用；部门归属不会自动加入资产。" editing={editing} onEdit={() => setEditing(true)} onCancel={() => { setRefs(agent[field]); setEditing(false); onDirty(false) }} onSave={save} /><div className="divide-y divide-border">{candidates.map((asset) => <div key={asset.id} className="flex items-center gap-4 px-5 py-4"><div className="min-w-0 flex-1"><Link to={`/assets/${asset.id}`} className="font-semibold hover:underline">{asset.name}</Link><p className="mt-1 text-xs text-muted-foreground">{asset.sourceType} · {asset.scope} · {asset.path}</p>{kind === 'Skills' && asset.skill?.installation.status === 'available' && <p className="mt-1 text-xs text-danger">引用失效 · Skill 本体未安装</p>}{kind === 'Skills' && asset.skill?.installation.status === 'update-available' && <p className="mt-1 text-xs text-warning">本体有可用更新</p>}</div>{editing ? <input type="checkbox" checked={refs.includes(asset.id)} onChange={() => toggle(asset.id)} aria-label={`${refs.includes(asset.id) ? '移除' : '添加'} ${asset.name}`} /> : <StatusBadge tone={refs.includes(asset.id) ? 'success' : 'neutral'}>{refs.includes(asset.id) ? '已引用' : '未引用'}</StatusBadge>}</div>)}</div>{kind === 'Skills' && <div className="border-t border-border p-4"><Button asChild variant="outline"><Link to="/assets/skills?view=installed">浏览已管理 Skills</Link></Button></div>}{editing && candidates.some((item) => item.sourceType === '显式共享' && refs.includes(item.id)) && <div className="border-t border-border p-4"><Button variant="outline" onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'shared', assetId: refs.find((id) => state.assets.find((item) => item.id === id)?.sourceType === '显式共享') ?? candidates[0].id } })}>查看共享影响</Button></div>}</section>
}

function MemoryTab({ agent }: { agent: FullAgent }) {
  const { state, dispatch } = useApp(); const spaces = getEligibleMemorySpaces(state, agent.id); const candidates = state.memoryCandidates.filter((item) => spaces.some((space) => space.id === item.spaceId)); const [spaceId, setSpaceId] = useState(''); const governance = spaceId ? resolveMemoryGovernance(state, spaceId, agent.id) : undefined
  const create = () => { if (!spaceId || !governance?.reviewerAgentId) return; const id = `MC-${String(state.memoryCandidates.length + 30).padStart(3, '0')}`; dispatch({ type: 'CREATE_MEMORY_CANDIDATE', candidate: { id, spaceId, proposerAgentId: agent.id, reviewerAgentId: governance.reviewerAgentId, summary: `${agent.name} 提出的正式记忆修改`, current: '当前正式内容', proposed: '建议写回的新内容', status: '待审核' } }); setSpaceId('') }
  return <section className="panel overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-border px-5 py-4"><div><b>正式 MemorySpace</b><p className="mt-1 text-xs text-muted-foreground">正式修改只能创建候选并审核，不能直接保存。</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-medium">唯一目标空间<select aria-label="唯一目标 MemorySpace" className="mt-1 block h-10 max-w-72 px-3 text-sm" value={spaceId} onChange={(event) => setSpaceId(event.target.value)}><option value="">请选择</option>{spaces.map((space) => <option key={space.id} value={space.id}>{space.scopeType} · {space.owner}</option>)}</select></label><Button disabled={!governance?.canPropose} onClick={create}><Plus size={15} />提出修改</Button></div></div>{spaceId && governance?.errors.length ? <div role="alert" className="border-b border-danger/30 bg-danger/5 px-5 py-3 text-sm text-danger">{governance.errors.join(' ')}</div> : null}<div className="divide-y divide-border">{spaces.map((space) => <div key={space.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[1fr_auto]"><div><b>{space.scopeType}</b><p className="mt-1 text-xs text-muted-foreground">{space.owner} · 归口 {space.steward} · 审核 {space.reviewer}</p><MonoPath>{space.path}</MonoPath></div><StatusBadge tone="success">{space.revision}</StatusBadge></div>)}</div><div className="border-t border-border p-5"><div className="label mb-3">候选</div>{candidates.length ? <div className="space-y-2">{candidates.map((candidate) => <button key={candidate.id} onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'memory', candidateId: candidate.id } })} className="flex w-full items-center justify-between rounded-lg border border-border p-3 text-left hover:bg-muted"><span><b>{candidate.id}</b><small className="ml-2 text-muted-foreground">{candidate.summary}</small></span><StatusBadge tone={candidate.status === '待审核' ? 'warning' : 'success'}>{candidate.status}</StatusBadge></button>)}</div> : <p className="text-sm text-muted-foreground">没有相关候选。</p>}</div></section>
}

function PermissionsTab({ agent, onDirty }: { agent: FullAgent; onDirty: (value: boolean) => void }) {
  const { dispatch } = useApp(); const [editing, setEditing] = useState(false); const [files, setFiles] = useState(agent.permissions.files); const [confirmOpen, setConfirmOpen] = useState(false); const [confirmName, setConfirmName] = useState(''); const [understood, setUnderstood] = useState(false)
  const commit = () => { dispatch({ type: 'UPDATE_AGENT', agentId: agent.id, changes: { permissions: { ...agent.permissions, files } }, message: `${files.includes('任意') ? '权限扩大已确认' : '权限已收紧'} · 仅当前页面内存 · 未写入真实配置` }); setEditing(false); setConfirmOpen(false); setConfirmName(''); setUnderstood(false); onDirty(false) }
  const save = () => { if (files.includes('任意')) { setConfirmOpen(true); return } commit() }
  const confirmed = confirmName.trim() === agent.name && understood
  return <><div className="grid gap-5 lg:grid-cols-2"><section className="panel p-5"><div className="flex items-center gap-2"><ShieldCheck className="text-success" /><b>当前有效边界</b></div><FieldRow label="文件写入">{agent.permissions.files}</FieldRow><FieldRow label="命令">{agent.permissions.commands}</FieldRow><FieldRow label="网络">{agent.permissions.network}</FieldRow><FieldRow label="委派">{agent.permissions.delegation}</FieldRow></section><section className="panel p-5"><div className="label">边界调整</div><p className="mt-3 text-sm leading-6 text-muted-foreground">收紧可直接模拟保存；扩大到 Workspace 外需要高风险确认。</p>{editing ? <><select value={files} onChange={(e) => { setFiles(e.target.value); onDirty(true) }} className="mt-5 h-10 w-full px-3"><option>只读当前 Workspace</option><option>仅当前 Workspace</option><option>任意目录</option></select><div className="mt-4 flex gap-2"><Button variant="outline" onClick={() => { setFiles(agent.permissions.files); setEditing(false); onDirty(false) }}>取消</Button><Button onClick={save}>保存边界</Button></div></> : <Button className="mt-5" variant="outline" onClick={() => setEditing(true)}><KeyRound size={16} />调整权限</Button>}</section></div><AppDialog open={confirmOpen} onOpenChange={(open) => { setConfirmOpen(open); if (!open) { setConfirmName(''); setUnderstood(false) } }} title="确认扩大文件权限" description="这会把演示配置从当前 Workspace 扩大到任意目录；不会写入真实配置。" footer={<><Button variant="outline" onClick={() => setConfirmOpen(false)}>返回编辑</Button><Button variant="danger" disabled={!confirmed} onClick={commit}>确认扩大权限</Button></>}><div className="rounded-lg border border-danger/30 bg-danger/5 p-4 text-sm leading-6"><b>影响范围</b><p className="mt-2 text-muted-foreground">Agent：{agent.name}<br />文件写入：{agent.permissions.files} → 任意目录<br />仅更新当前页面内存，刷新后恢复初始状态。</p></div><label className="mt-5 block text-sm font-medium" htmlFor="permission-confirm-name">输入 Agent 名称“{agent.name}”确认<input id="permission-confirm-name" className="mt-2 h-10 w-full px-3" value={confirmName} onChange={(event) => setConfirmName(event.target.value)} autoComplete="off" /></label><label className="mt-4 flex items-start gap-3 text-sm leading-6"><input className="mt-1" type="checkbox" checked={understood} onChange={(event) => setUnderstood(event.target.checked)} /><span>我了解这是高风险权限扩大，但当前演示不会写入真实配置。</span></label></AppDialog></>
}

function WorkspacesTab({ agent }: { agent: FullAgent }) { const { state } = useApp(); return <section className="panel divide-y divide-border">{agent.workspaceBindings.map((binding) => { const workspace = state.workspaces.find((item) => item.id === binding.workspaceId); return <div key={binding.workspaceId} className="grid gap-4 p-5 md:grid-cols-[1fr_1fr_auto]"><div><Link to={`/workspaces/${binding.workspaceId}?tab=agents`} className="font-semibold hover:underline">{workspace?.name ?? binding.workspaceId}</Link><p className="mt-1 text-xs text-muted-foreground">项目记忆 {binding.memoryRevision}</p></div><div className="text-sm text-muted-foreground">Rules {binding.ruleIds.length} · Skills {binding.skillIds.length} · MCP {binding.mcpIds.length}<p className="mt-1 line-clamp-2">{binding.instructions}</p></div><StatusBadge tone={binding.ruleIds.length ? 'success' : 'warning'}>{binding.ruleIds.length ? '配置完整' : '缺少 Rules'}</StatusBadge></div> })}{!agent.workspaceBindings.length && <div className="p-5 text-sm text-muted-foreground">尚未创建 Agent × Workspace 专属配置。</div>}</section> }
function SopTab({ agent }: { agent: FullAgent }) { const { state } = useApp(); return <section className="panel divide-y divide-border">{agent.sopRefs.map((id) => { const asset = state.assets.find((item) => item.id === id); return <div key={id} className="flex items-center justify-between gap-4 p-5"><div><Link to={`/assets/${id}`} className="font-semibold hover:underline">{asset?.name ?? id}</Link><p className="mt-1 text-xs text-muted-foreground">{asset?.scope} · {asset?.version ?? '无版本'}</p></div><StatusBadge tone="success">显式引用</StatusBadge></div> })}<MockBoundaryNote>SOP 只定义工作方式，不在 Desktop 中选择本次人员、启动或推进执行。</MockBoundaryNote></section> }
function TabHeader({ title, description, editing, onEdit, onCancel, onSave }: { title: string; description: string; editing: boolean; onEdit: () => void; onCancel: () => void; onSave: () => void }) { return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-muted/25 px-5 py-4"><div><b>{title}</b><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>{editing ? <div className="flex gap-2"><Button variant="outline" onClick={onCancel}>取消</Button><Button onClick={onSave}><Save size={15} />模拟保存</Button></div> : <Button variant="outline" size="sm" onClick={onEdit}>编辑</Button>}</div> }
function Labeled({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium">{label}<div className="mt-2">{children}</div></label> }
function ListEditor({ label, values, onChange }: { label: string; values: string[]; onChange: (values: string[]) => void }) { return <Labeled label={label}><textarea value={values.join('\n')} onChange={(event) => onChange(event.target.value.split('\n').map((item) => item.trim()).filter(Boolean))} className="min-h-28 w-full p-3" /></Labeled> }
