import { Building2, Plus, Users } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Button } from '../../components/ui/button'
import { EntityNotFound, EntityTabs, FieldRow, PageHeader, StatusBadge } from '../../components/app/page'
import { useApp } from '../../state'
import type { FullDepartment } from '../../domain'

export function OrganizationPage() {
  const { state, dispatch } = useApp(); const [params, setParams] = useSearchParams(); const companyId = params.get('company') ?? state.companies[0]?.id; const company = state.companies.find((item) => item.id === companyId)
  const roots = state.departments.filter((item) => item.companyId === companyId && !item.parentDepartmentId)
  return <><PageHeader title="组织" description="管理多个 Company、无环部门树、主管、成员与明确委派边界；关系本身不授予权限。" action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'organization', entity: 'company', mode: 'create' } })}><Plus size={15} />创建公司</Button><Button onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'organization', entity: 'department', mode: 'create' } })}><Plus size={15} />创建部门</Button></div>} />
    <div className="grid gap-5 lg:grid-cols-[300px_1fr]"><aside className="panel h-fit overflow-hidden"><div className="border-b border-border p-3"><select aria-label="当前公司" value={companyId} onChange={(e) => setParams({ company: e.target.value })} className="h-10 w-full px-3">{state.companies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="p-2">{roots.map((root) => <DepartmentNode key={root.id} department={root} depth={0} />)}</div></aside>
      {company ? <section className="panel p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="label">Company</div><h3 className="mt-2 text-xl font-semibold">{company.name}</h3></div><Button asChild variant="outline"><Link to={`/organization/companies/${company.id}`}>查看公司详情</Link></Button></div><p className="mt-5 max-w-3xl leading-7">{company.mission}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="部门" value={company.departmentIds.length} /><Metric label="Workspaces" value={state.workspaces.filter((item) => item.companyId === company.id).length} /><Metric label="共享资产" value={state.assets.filter((item) => item.companyId === company.id && item.sourceType === '显式共享').length} /></div><div className="mt-7 rounded-lg border border-border bg-muted/35 p-4 text-sm leading-6"><b>边界</b><p className="mt-2 text-muted-foreground">{company.boundary}</p></div></section> : <EntityNotFound entity="Company" backTo="/organization" />}
    </div></>
}

function DepartmentNode({ department, depth }: { department: FullDepartment; depth: number }) { const { state } = useApp(); const children = state.departments.filter((item) => item.parentDepartmentId === department.id); return <div><Link to={`/organization/departments/${department.id}`} style={{ paddingLeft: `${12 + depth * 18}px` }} className="flex min-h-10 items-center gap-2 rounded-md pr-3 text-sm hover:bg-muted"><Building2 size={14} /><span className="min-w-0 flex-1 truncate">{department.name}</span><small className="text-muted-foreground">{department.memberAgentIds.length}</small></Link>{children.map((item) => <DepartmentNode key={item.id} department={item} depth={depth + 1} />)}</div> }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-muted p-4"><b className="text-xl">{value}</b><p className="mt-1 text-xs text-muted-foreground">{label}</p></div> }

const companyTabs = [['overview', '概览'], ['organization', '组织'], ['workspaces', 'Workspaces'], ['shared', '共享资产'], ['permissions', '权限']].map(([id, label]) => ({ id, label }))
export function CompanyDetailPage() { const { id } = useParams(); const { state, dispatch } = useApp(); const [params, setParams] = useSearchParams(); const company = state.companies.find((item) => item.id === id); if (!company) return <EntityNotFound entity="Company" backTo="/organization" />; const tab = companyTabs.some((item) => item.id === params.get('tab')) ? params.get('tab')! : 'overview'; const deps = state.departments.filter((item) => item.companyId === company.id); const workspaces = state.workspaces.filter((item) => item.companyId === company.id); const shared = state.assets.filter((item) => item.companyId === company.id && item.sourceType === '显式共享'); return <><PageHeader backTo="/organization" title={company.name} description="公司公共配置只承载普通默认、显式共享资产和不可突破的安全边界。" action={<Button variant="outline" onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'organization', entity: 'company', id: company.id, mode: 'edit' } })}>编辑公司</Button>} /><EntityTabs tabs={companyTabs} active={tab} onChange={(next) => setParams(next === 'overview' ? {} : { tab: next })} />{tab === 'overview' && <section className="panel p-5"><FieldRow label="使命">{company.mission}</FieldRow><FieldRow label="董事长助理">{state.agents.find((item) => item.id === company.assistantAgentId)?.name ?? '未设置'}</FieldRow><FieldRow label="部门">{deps.length}</FieldRow><FieldRow label="Workspace">{workspaces.length}</FieldRow><FieldRow label="边界">{company.boundary}</FieldRow></section>}{tab === 'organization' && <Rows items={deps.map((item) => ({ id: item.id, title: item.name, meta: `${item.parentDepartmentId ? '下级部门' : '顶级部门'} · ${item.memberAgentIds.length} Agents`, to: `/organization/departments/${item.id}` }))} />}{tab === 'workspaces' && <Rows items={workspaces.map((item) => ({ id: item.id, title: item.name, meta: `${item.department ?? '未设置主责'} · ${item.health}`, to: `/workspaces/${item.id}` }))} />}{tab === 'shared' && <Rows items={shared.map((item) => ({ id: item.id, title: item.name, meta: `${item.kind} · ${item.references.length} 个引用`, to: `/assets/${item.id}` }))} />}{tab === 'permissions' && <section className="panel p-5"><b>不可突破的安全边界</b><div className="mt-4 space-y-3">{['权限只能收紧，不能由 Agent 自行扩大', '跨 Company 共享必须单独注册并授权', '生产和外部发布必须确认', '凭据、Token 与钥匙串数据不可备份'].map((item) => <div key={item} className="flex gap-3 rounded-lg border border-border p-3"><StatusBadge tone="success">固定</StatusBadge><span>{item}</span></div>)}</div></section>}</> }

export function DepartmentDetailPage() { const { id } = useParams(); const { state, dispatch } = useApp(); const dep = state.departments.find((item) => item.id === id); const memory = state.memorySpaces.filter((item) => item.scopeType === 'Department × Workspace' && item.owner.startsWith(dep?.name ?? '')); const grants = state.agents.flatMap((agent) => agent.serviceGrants.filter((grant) => grant.departmentId === dep?.id).map((grant) => ({ agent, grant }))); if (!dep) return <EntityNotFound entity="Department" backTo="/organization" />; const parent = state.departments.find((item) => item.id === dep.parentDepartmentId); const members = state.agents.filter((item) => dep.memberAgentIds.includes(item.id)); return <><PageHeader backTo="/organization" title={dep.name} description={`${state.companies.find((item) => item.id === dep.companyId)?.name} · 委派深度 ${dep.delegationDepth}`} action={<div className="flex gap-2"><Button variant="outline" onClick={() => dispatch({ type: 'OPEN_DIALOG', dialog: { kind: 'organization', entity: 'department', id: dep.id, mode: 'edit' } })}>编辑部门</Button><Button asChild><Link to={`/agents/new?department=${dep.id}`}><Plus size={15} />添加 Agent</Link></Button></div>} /><div className="grid gap-5 xl:grid-cols-[1fr_360px]"><section className="panel p-5"><FieldRow label="上级">{parent?.name ?? 'Company 顶级'}</FieldRow><FieldRow label="主管">{state.agents.find((item) => item.id === dep.managerAgentId)?.name ?? dep.manager ?? '未设置'}</FieldRow><FieldRow label="使命">{dep.mission}</FieldRow><FieldRow label="职责">{dep.responsibilities.join('；') || '未设置'}</FieldRow><FieldRow label="边界">{dep.boundaries.join('；') || '未设置'}</FieldRow><FieldRow label="拥有 SOP">{dep.ownedSopIds.map((assetId) => state.assets.find((item) => item.id === assetId)?.name).filter(Boolean).join('、') || '无'}</FieldRow></section><aside className="space-y-5"><section className="panel p-5"><div className="flex items-center gap-2"><Users size={17} /><b>成员与岗位</b></div><div className="mt-4 space-y-2">{members.map((agent) => <Link key={agent.id} to={`/agents/${agent.id}`} className="flex justify-between rounded-lg border border-border p-3 hover:bg-muted"><span>{agent.name}</span><small className="text-muted-foreground">{agent.role}</small></Link>)}{!members.length && <p className="text-sm text-muted-foreground">暂无长期 Agent。</p>}</div></section><section className="panel p-5"><b>显式服务授权</b><div className="mt-3 text-sm text-muted-foreground">{grants.map(({ agent, grant }) => <p key={grant.id}>{agent.name}：{grant.capabilities.join('、')} · {grant.status}</p>)}{!grants.length && '无外部 Agent 获得服务授权。'}</div></section><section className="panel p-5"><b>Department × Workspace Memory</b>{memory.map((item) => <p key={item.id} className="mt-3 text-sm">{item.owner} · {item.revision}</p>)}{!memory.length && <p className="mt-3 text-sm text-muted-foreground">暂无正式部门项目记忆。</p>}</section></aside></div></> }

function Rows({ items }: { items: { id: string; title: string; meta: string; to: string }[] }) { return <section className="panel divide-y divide-border">{items.map((item) => <Link key={item.id} to={item.to} className="flex items-center justify-between gap-4 p-5 hover:bg-muted"><b>{item.title}</b><span className="text-sm text-muted-foreground">{item.meta}</span></Link>)}{!items.length && <p className="p-5 text-sm text-muted-foreground">暂无关联对象。</p>}</section> }
